BEGIN TRANSACTION;
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (0,'Pivo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (1,'Hospoda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (2,'Outdoor',3,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (3,'Alkohol',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (4,'Magic: the gathering',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (5,'Larp',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (6,'Nekuřácká akce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (7,'Divadlo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (8,'Indoor',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (9,'Opera',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (10,'Deskovky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (11,'Deskové hry',1,10);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (12,'Muzeum',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (13,'Sport',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (14,'Počítač',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (15,'Technologie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (16,'Hala',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (17,'Tělocvična',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (18,'Hřiště',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (19,'Voda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (20,'Řeka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (21,'Rybník',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (22,'Jezero',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (23,'Skála',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (24,'Výšlap',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (25,'Hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (26,'Zvířata',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (27,'Les',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (28,'Rock',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (29,'Jídlo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (30,'Metal',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (31,'Punk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (32,'Kino',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (33,'Město',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (34,'Ostrava',1,33);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (35,'Praha',1,33);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (36,'Brno',1,33);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (37,'Olomouc',1,33);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (38,'Křesťanství',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (39,'Vánoce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (40,'Vzdělávání',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (41,'Maso',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (42,'Děti',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (43,'Akce pro děti',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (44,'Islám',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (45,'Tábor',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (46,'Historie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (47,'Hrady',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (48,'Památky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (49,'Unesco',1,48);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (50,'Hory',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (51,'Park',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (52,'Tvrdý alkohol',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (53,'Režná',1,52);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (54,'Vodka',1,52);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (55,'Rum',1,52);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (56,'Demonstrace',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (57,'Cyklistika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (58,'Věda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (59,'Apple',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (60,'Geocache',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (61,'Bezalkoolová',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (62,'Festival',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (63,'Hudební festival',1,62);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (64,'Keltský',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (65,'Umění',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (66,'Létání',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (67,'Tanec',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (68,'Limonáda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (69,'Kopec',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (70,'Rozhledna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (71,'Výstava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (72,'Film',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (73,'Bitva',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (74,'Dospělí',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (75,'Poker',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (76,'Lanka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (77,'Řemesla',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (78,'Sraz',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (79,'Středověk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (80,'Fantasy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (81,'Troll',1,80);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (82,'Mág',1,80);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (83,'Špičatý klobouk',1,80);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (84,'Trpaslíci',1,80);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (85,'Výlet',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (86,'Vojenské',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (87,'Armáda',1,86);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (88,'Déšť',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (89,'Slunce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (90,'Sníh',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (91,'Mráz',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (92,'Vlak',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (93,'Oslava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (94,'Dřevárna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (95,'Zámek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (96,'Hrad',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (97,'Zoo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (98,'Jóga',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (99,'Cvičení',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (100,'Brigáda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (101,'Workout',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (102,'Wod',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (103,'Upír',1,102);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (104,'Upírka',1,102);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (105,'Upíři',1,102);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (106,'Noc',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (107,'Den',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (108,'Omg',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (109,'Prohlídka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (110,'Víno',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (111,'Programování',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (112,'Myslivost',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (113,'Flóra',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (114,'Válka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (115,'Auto',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (116,'Auta',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (117,'Senoseč',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (118,'Trnkobraní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (119,'Baroko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (120,'Vinobraní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (121,'Renesance',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (122,'Gotika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (123,'Koncert',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (124,'Starověk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (125,'Velká morava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (126,'Humanismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (127,'Baterka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (128,'Jeskyně',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (129,'Filozofie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (130,'Louč',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (131,'Psychologie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (132,'Oheň',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (133,'Táborák',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (134,'Malby',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (135,'Kresby',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (136,'Příměstský',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (137,'Sochy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (138,'Španělsko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (139,'Řecko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (140,'Irsko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (141,'Balkán',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (142,'Vikingové',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (143,'Mayové',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (144,'Inkové',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (145,'Král',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (146,'Aztékové',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (147,'Nemocnice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (148,'Betlém',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (149,'Osel',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (150,'Bylinky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (151,'Bor',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (152,'Hvězdy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (153,'Víla',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (154,'Farma',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (155,'Trh',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (156,'Jarmark',1,155);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (157,'Pouť',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (158,'Pantonima',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (159,'Princ',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (160,'Amerika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (161,'Evropa',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (162,'Labyrint',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (163,'Antarktida',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (164,'Karetní hry',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (165,'Arktida',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (166,'Skyrim',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (167,'Kostým',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (168,'Atlantida',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (169,'Pramen',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (170,'Studánka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (171,'Klášter',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (172,'Kostel',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (173,'Ulička',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (174,'Uličky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (175,'Kašna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (176,'Horolezectví',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (177,'Ekumenické',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (178,'Poutní místo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (179,'Pověst',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (180,'Ledovec',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (181,'Malba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (182,'Lukostřelba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (183,'Kaple',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (184,'Šerm',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (185,'Jazyk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (186,'Venkov',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (187,'Rybářství',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (188,'Kanoe',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (189,'Klaun',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (190,'Cirkus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (191,'Vodáctví',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (192,'Kejklíř',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (193,'Indiáni',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (194,'Zabíjačka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (195,'Krasojezdkyně',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (196,'Táboření',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (197,'Zážitkovka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (198,'Kemp',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (199,'Mažoretky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (200,'Hody',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (201,'Metro',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (202,'Posvícení',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (203,'Sklep',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (204,'Tramvaj',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (205,'Sklípek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (206,'Šifrovačka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (207,'Koupaliště',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (208,'Bazén',1,207);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (209,'Extremismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (210,'Imigranti',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (211,'Zahrádka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (212,'Pěstitelství',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (213,'Psi',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (214,'Kočky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (215,'Zvířátka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (216,'Morčata',1,215);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (217,'Fauna',1,215);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (218,'Plazi',1,215);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (219,'Žába',1,215);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (220,'Ptáci',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (221,'Kuřátka',1,220);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (222,'Internet',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (223,'Vaření',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (224,'Stavebnice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (225,'Cheva',1,224);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (226,'Merkur',1,224);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (227,'Koupání',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (228,'Mlýn',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (229,'Slavnost',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (230,'Pohřeb',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (231,'Hrášek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (232,'Židi',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (233,'Inkvizice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (234,'Technika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (235,'Boty',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (236,'Oblečení',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (237,'Móda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (238,'Lasergame',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (239,'Lynčování',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (240,'Lego',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (241,'Kostnice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (242,'Zájezd',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (243,'Moře',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (244,'Sklo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (245,'Keramika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (246,'Kování',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (247,'Měď',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (248,'Bronz',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (249,'Železo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (250,'Uhlí',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (251,'Důl',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (252,'Ropa',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (253,'Sůl',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (254,'Loď',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (255,'Magnet',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (256,'Piráti',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (257,'Standup komedie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (258,'Zlato',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (259,'Šití',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (260,'Len',1,259);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (261,'Netex',1,259);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (262,'Plátno',1,259);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (263,'Platina',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (264,'Šaty',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (265,'Aktinium',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (266,'Chemie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (267,'Kouzla',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (268,'Politika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (269,'Guláš',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (270,'Komunismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (271,'Kapitalismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (272,'Hackathon',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (273,'Anglie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (274,'Maraton',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (275,'Morava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (276,'Bunkr',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (277,'Prales',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (278,'Poušť',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (279,'Škola',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (280,'Školka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (281,'Gymnázium',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (282,'Pochod',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (283,'Ekologie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (284,'Ekonomie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (285,'Mykologie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (286,'Zahrada',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (287,'Skleník',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (288,'Lopata',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (289,'Výkop',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (290,'Přehlídka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (291,'Úklid',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (292,'Cestopis',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (293,'Elektrárna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (294,'Piknik',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (295,'Práce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (296,'Teplárna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (297,'Pivovar',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (298,'Masáž',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (299,'Lázně',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (300,'Termály',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (301,'Wellness',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (302,'Pláž',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (303,'Slunění',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (304,'Sauna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (305,'Anime',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (306,'Tenis',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (307,'Hokej',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (308,'Floorball',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (309,'Víkend',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (310,'Solná jeskyně',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (311,'Týpí',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (312,'Stan',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (313,'Stanování',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (314,'Pohorky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (315,'Furry',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (316,'Strašidla',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (317,'Volejbal',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (318,'Koště',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (319,'Přehrada',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (320,'Hasiči',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (321,'Večerníček',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (322,'Soutěž krásy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (323,'Vinice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (324,'Příroda',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (325,'Vodopád',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (326,'Kameny',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (327,'Chmelobraní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (328,'Sci-fi',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (329,'Chata',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (330,'Golf',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (331,'Chalupa',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (332,'Inline',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (333,'Byt',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (334,'Liberec',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (335,'Pára',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (336,'Parní stroj',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (337,'Zážitek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (338,'Adrenalin',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (339,'Vzrušení',1,338);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (340,'Skoba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (341,'Extáze',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (342,'Hra',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (343,'Cyklobus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (344,'Lanovka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (345,'Koloběžky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (346,'Skanzen',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (347,'Techno',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (348,'Dnb',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (349,'Věž',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (350,'Rnb',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (351,'Dračí doupě',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (352,'Dubstep',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (353,'Společenské hry',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (354,'Ples',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (355,'Zábava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (356,'Čoch',1,355);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (357,'Diskotéka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (358,'Bál',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (359,'Paintball',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (360,'Laser',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (361,'Laser game',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (362,'Motokáry',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (363,'Hacker',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (364,'Google',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (365,'Microsoft',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (366,'Včela',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (367,'Panna',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (368,'Chrám',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (369,'Citadela',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (370,'Svatba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (371,'Rodinná oslava',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (372,'Seriály',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (373,'Cadillac',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (374,'Star trek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (375,'Dinosaurus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (376,'Game of thrones',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (377,'Zaklínač',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (378,'Housle',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (379,'Varhany',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (380,'Mše',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (381,'Kost',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (382,'Kukuřice',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (383,'Šelma',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (384,'Lev',1,383);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (385,'Tygr',1,383);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (386,'Dravec',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (387,'Kaktusy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (388,'Dovednost',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (389,'Zeď',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (390,'Sekera',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (391,'Trabant',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (392,'Lesnictví',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (393,'Veteráni',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (394,'Dřevorubectví',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (395,'Fotografování',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (396,'Východ',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (397,'Orient',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (398,'Indie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (399,'Tibet',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (400,'Čína',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (401,'Rusko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (402,'Sibiř',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (403,'Terminátor',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (404,'Lindemann',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (405,'Radar',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (406,'Saň',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (407,'Mash',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (408,'Facebook skupina \"jsi holka? přidej se.\"', 2, NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (409,'Pár pařmenů',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (410,'Rytíř',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (411,'Kofola',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (412,'Fofola',1,411);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (413,'Kokain',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (414,'Hifi věž',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (415,'Pán prstenů',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (416,'Zakažte akčník',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (417,'Battlestar galactica',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (418,'Rally',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (419,'Voleyball',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (420,'Beach',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (421,'Borůvky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (422,'Bažantrikulace',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (423,'Konec světa',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (424,'Konspirace',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (425,'Špioni',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (426,'Vesmír',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (427,'Anarchismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (428,'Squat',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (429,'Jupiter',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (430,'Káva',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (431,'Čaj',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (432,'Dýmka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (433,'Humbuk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (434,'Happening',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (435,'Kratochvíle',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (436,'Kniha',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (437,'Protest',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (438,'Svitek',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (439,'Pergamen',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (440,'Papyrus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (441,'Den země',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (442,'Kytara',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (443,'Řezbář',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (444,'Svíce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (445,'Šňupání',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (446,'Ping pong',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (447,'Loutka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (448,'Loutky',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (449,'Open-air',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (450,'Pro dospělé',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (451,'Pro děti',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (452,'Pro rodiče s dětmi',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (453,'Občerstvení',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (454,'Vnitřní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (455,'Společenské oblečení',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (456,'Instrumentální',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (457,'Vokální',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (458,'Commedia dell''arte',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (459,'Komedie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (460,'Drama',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (461,'Parodie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (462,'Dobrodružný film',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (463,'Western',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (464,'Kovbojka',1,463);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (465,'Historický film',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (466,'Životopisný film',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (467,'Hudební film',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (468,'Pohádka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (469,'Drak',1,468);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (470,'Princezna',1,468);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (471,'Obr',1,468);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (472,'Čarodějnice',1,468);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (473,'Dračice',1,468);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (474,'Láska',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (475,'Raut',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (476,'Obrazy',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (477,'Architektura',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (478,'Fotografie',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (479,'Řemeslo',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (480,'Románský sloh',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (481,'Gotický sloh',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (482,'Novověk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (483,'Rokoko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (484,'Klasicismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (485,'Romantismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (486,'Realismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (487,'Impresionismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (488,'Symbolismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (489,'Secese',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (490,'Art deco',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (491,'Dadaismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (492,'Funkcionalismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (493,'Surrealismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (494,'Vstupné dobrovolné',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (495,'Sportovní akce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (496,'Relaxační',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (497,'Adrenalinový',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (498,'Letní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (499,'Zimní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (500,'Kolektivní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (501,'Orientační',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (502,'Vodní',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (503,'Míčový',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (504,'Bojová umění',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (505,'Silový',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (506,'Motorismus',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (507,'Tanced',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (508,'Turistický',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (509,'Fandění',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (510,'První liga',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (511,'Druhá liga',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (512,'Extraliga',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (513,'Mládež',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (514,'Závod',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (515,'Mírný terén',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (516,'Střední terén',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (517,'Náročný terén',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (518,'Ceny pro vítěze',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (519,'Uzavřená akce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (520,'Třídní sraz',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (521,'Pracovní schůzka',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (522,'Firemní akce',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (523,'Den otevřených dveří',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (524,'Tuning',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (525,'Letecký den',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (526,'Farmářský trh',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (527,'Blues',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (528,'Country',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (529,'Disco',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (530,'Dechová hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (531,'Dechovka',1,530);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (532,'Eva a vašek',1,530);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (533,'Duchovní hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (534,'Elektronická hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (535,'Folk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (536,'Funk',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (537,'Hip hop',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (538,'Jazz',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (539,'Pop',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (540,'Reggae',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (541,'R&b',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (542,'Ska',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (543,'Underground',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (544,'Vážná hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (545,'World music',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (546,'Epická hudba',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (547,'Středověké zbraně',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (548,'Meč',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (549,'Luk',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (550,'Zbroj',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (551,'Štít',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (552,'Šíp',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (553,'Katapult',1,547);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (554,'Počítačové hry',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (555,'Ork',1,554);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (556,'Warcraft',1,554);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (557,'Wot',1,554);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (558,'Minecraft',1,554);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (559,'Nealko',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (560,'Kapely',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (561,'Nightwish',1,560);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (562,'Rammstein',1,560);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (563,'Asonance',1,560);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (564,'Horkýže',1,560);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (565,'Násilí',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (566,'Erotika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (567,'Mystika',2,NULL);
INSERT INTO tags("id","name","type","parentSynonymId") VALUES (568,'Párty',2,NULL);
COMMIT TRANSACTION;
